#!/usr/bin/env node

var parse = require('./'),
    d3ize = require('./d3ize'),
    concat = require('concat-stream');

process.stdin.pipe(concat(function(gedcom) {
    var input = gedcom.toString();
    if (input.charCodeAt(0) == 65279) input = input.substring(1);
    var output = d3ize(parse(input));
    console.log(JSON.stringify(output, null, 2));
}));
